sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - stable
script:
  - cargo build
  - cargo doc
  - cargo test --all-features
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then (cargo bench); fi
